### ISSUE TITLE
utilities.py throws error when trying to load citations

### ISSUE THREAD

**Issue by dwesterfield** [Tutt-Library/cc-scholarship-graph#7]
when trying to run initialize(). forgot which way the slashes go but got pretty much the same error trying both slash directions.

Traceback (most recent call last):
  File "C:\CCKnowledgeGraph\PY3-ENV\lib\site-packages\click\core.py", line 696, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "C:\CCKnowledgeGraph\PY3-ENV\lib\site-packages\click\core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "C:\CCKnowledgeGraph\PY3-ENV\lib\site-packages\click\core.py", line 885, in parse_args
    ' '.join(map(make_str, args))))
  File "C:\CCKnowledgeGraph\PY3-ENV\lib\site-packages\click\core.py", line 476, in fail
    raise UsageError(message, self)
click.exceptions.UsageError: Got unexpected extra arguments (C : \ C C K n o w l e d g e G r a p h \ K n o w l e d g e G r a p h \ c c - p e o p l e . t t l)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#6>", line 1, in <module>
    utilities.initialize("C:\CCKnowledgeGraph\KnowledgeGraph\cc-people.ttl","C:\CCKnowledgeGraph\cc-scholarship-graph\data\creative_works.ttl","C:\CCKnowledgeGraph\Temp\articles.txt")
  File "C:\CCKnowledgeGraph\PY3-ENV\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\CCKnowledgeGraph\PY3-ENV\lib\site-packages\click\core.py", line 707, in main
    e.show()
  File "C:\CCKnowledgeGraph\PY3-ENV\lib\site-packages\click\exceptions.py", line 43, in show
    file = get_text_stderr()
  File "C:\CCKnowledgeGraph\PY3-ENV\lib\site-packages\click\_compat.py", line 391, in get_text_stderr
    rv = _get_windows_console_stream(sys.stderr, encoding, errors)
  File "C:\CCKnowledgeGraph\PY3-ENV\lib\site-packages\click\_winconsole.py", line 261, in _get_windows_console_stream
    func = _stream_factories.get(f.fileno())
io.UnsupportedOperation: fileno

**Comment by dwesterfield** [comment]
fixed
